name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche "main"

jobs:
  build:

    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'  # La version Flutter que vous utilisez

    # 🔥 Nettoie le projet et force la récupération des dépendances
    - name: Clean Flutter project
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    # 🔥 Met à jour les dépendances pour éviter les erreurs avec Syncfusion
    - name: Upgrade dependencies
      run: flutter pub upgrade

    # 🔥 Vérifie la version de Flutter (utile pour debug)
    - name: Check Flutter version
      run: flutter --version

    - name: Create .env file  # 🔥 Génère un fichier .env à partir du secret
      run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > env_config.txt
          echo "THE_GRAPH_API_KEY=${{ secrets.THE_GRAPH_API_KEY }}" >> env_config.txt
          echo "THE_GRAPH_API_KEY2=${{ secrets.THE_GRAPH_API_KEY }}" >> env_config.txt

    - name: Decode and write google-services.json
      run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

    # 🔥 Compilation avec verbose pour voir les erreurs plus détaillées
    - name: Build web app
      run: flutter build web --release --web-renderer html --base-href /realtoken_apps/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web  # Chemin vers les fichiers web générés
