name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche "main"

jobs:
  build:
    env:
      THE_GRAPH_API_KEY: ${{ secrets.THE_GRAPH_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }} 

    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # La version Flutter que vous utilisez

    - name: Install dependencies
      run: flutter pub get

    - name: Decode and write google-services.json
      run: |
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" > .env
          echo "THE_GRAPH_API_KEY=$THE_GRAPH_API_KEY" >> .env  # 🔥 Ajoute la seconde clé API


    - name: Build web app
      run: flutter build web --release --web-renderer html --base-href /realtoken_apps/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web  # Chemin vers les fichiers web générés
