name: Build and Deploy Android App Bundle

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android App Bundle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Add google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

    - name: Decode and add the signing key
      run: |
        mkdir -p android/app
        echo "${{ secrets.MY_RELEASE_KEY }}" | base64 --decode > android/app/my-release-key.jks

    - name: Set up environment for signing
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=android/app/my-release-key.jks" >> android/key.properties

    - name: Build app bundle
      run: flutter build appbundle --release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
